# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_lrh', '0002_auto_20180417_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_time']},
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
